# Generated by Django 4.2.7 on 2023-12-11 07:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='code',
            name='phone_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
        ),
    ]
